# This is a basic workflow to help you get started with Actions

name: Docs

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx-gherkindoc

      - name: Create docs from feature files
        run: make featuredocs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes
          file_pattern: docs/features/*
          
